'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System

Namespace UseLinkEvents

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class PrintRibbonControllerResources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(UseLinkEvents.PrintRibbonControllerResources.resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UseLinkEvents.PrintRibbonControllerResources", GetType(UseLinkEvents.PrintRibbonControllerResources).Assembly)
                    UseLinkEvents.PrintRibbonControllerResources.resourceMan = temp
                End If

                Return UseLinkEvents.PrintRibbonControllerResources.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return UseLinkEvents.PrintRibbonControllerResources.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                UseLinkEvents.PrintRibbonControllerResources.resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ClosePreview As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ClosePreview", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ClosePreviewLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ClosePreviewLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Customize As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Customize", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_CustomizeLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_CustomizeLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Document As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Document", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_DocumentMap As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_DocumentMap", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_DocumentMapLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_DocumentMapLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_EditPageHF As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_EditPageHF", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_EditPageHFLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_EditPageHFLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportCsv As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportCsv", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportCsvLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportCsvLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportFile As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportFile", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportFileLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportFileLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportGraphic As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportGraphic", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportGraphicLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportGraphicLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportHtm As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportHtm", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportHtmLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportHtmLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportMht As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportMht", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportMhtLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportMhtLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportPdf As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportPdf", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportPdfLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportPdfLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportRtf As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportRtf", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportRtfLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportRtfLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportTxt As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportTxt", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportTxtLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportTxtLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportXls As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportXls", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportXlsLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportXlsLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportXlsx As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportXlsx", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportXlsxLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportXlsxLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_FillBackground As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_FillBackground", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_FillBackgroundLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_FillBackgroundLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Find As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Find", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_FindLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_FindLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_HandTool As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_HandTool", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Magnifier As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Magnifier", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_MultiplePages As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_MultiplePages", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_MultiplePagesLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_MultiplePagesLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Open As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Open", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_OpenLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_OpenLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMargins As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMargins", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMarginsLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsModerate As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMarginsModerate", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsNarrow As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMarginsNarrow", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsNormal As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMarginsNormal", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsWide As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMarginsWide", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientation As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageOrientation", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientationLandscape As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageOrientationLandscape", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientationLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageOrientationLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientationPortrait As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageOrientationPortrait", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageSetupDialog As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageSetupDialog", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A3 As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A3", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A4 As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A4", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A5 As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A5", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A6 As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A6", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Executive As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Executive", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Legal As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Legal", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Letter As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Letter", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Tabloid As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Tabloid", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperSize As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperSize", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperSizeLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperSizeLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Parameters As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Parameters", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ParametersLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ParametersLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Pointer As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Pointer", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Print As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Print", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PrintDirect As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PrintDirect", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PrintDirectLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PrintDirectLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PrintLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PrintLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PrintSetup As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PrintSetup", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PrintSetupLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PrintSetupLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Save As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Save", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SaveLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SaveLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Scale As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Scale", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ScaleLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ScaleLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendCsv As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendCsv", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendCsvLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendCsvLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendFile As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendFile", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendFileLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendFileLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendGraphic As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendGraphic", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendGraphicLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendGraphicLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendMht As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendMht", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendMhtLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendMhtLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendPdf As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendPdf", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendPdfLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendPdfLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendRtf As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendRtf", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendRtfLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendRtfLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendTxt As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendTxt", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendTxtLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendTxtLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendXls As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendXls", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendXlsLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendXlsLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendXlsx As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendXlsx", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendXlsxLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendXlsxLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowFirstPage As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowFirstPage", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowFirstPageLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowFirstPageLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowLastPage As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowLastPage", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowLastPageLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowLastPageLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowNextPage As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowNextPage", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowNextPageLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowNextPageLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowPrevPage As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowPrevPage", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowPrevPageLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowPrevPageLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Thumbnails As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Thumbnails", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ThumbnailsLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ThumbnailsLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Watermark As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Watermark", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_WatermarkLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_WatermarkLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Zoom As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Zoom", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ZoomIn As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ZoomIn", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ZoomInLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ZoomInLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ZoomLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ZoomLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ZoomOut As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ZoomOut", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ZoomOutLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = UseLinkEvents.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ZoomOutLarge", UseLinkEvents.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
